/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.4-94-g5d07afd482-20240331"
#endif /* AVUTIL_FFVERSION_H */
